spring:
  # H2 ?????? ?? (??? DB)
  datasource:
    url: jdbc:h2:mem:ticketdb;MODE=MySQL # MySQL ??? ??
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 ?? ??? (??? DB ?? ??)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA ??
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # ??? ? ??? ???, ? ? ?? (???)
    show-sql: true # ???? SQL ?? ??
    properties:
      hibernate:
        format_sql: true # SQL ??? ??

  thymeleaf:
    cache: false # [???] HTML ?? ?? (???? ?? ??)
    prefix: classpath:/templates/
    suffix: .html